using YuzuDelivery.Umbraco.BlockList;
using YuzuDelivery.Umbraco.Core;
using YuzuDelivery.Umbraco.Forms;
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.23.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace YuzuDelivery.ViewModels
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.23.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum vmBlock_GridBuilderSizes
    {
        _12 = 12,
    
        _11 = 11,
    
        _10 = 10,
    
        _9 = 9,
    
        _8 = 8,
    
        _7 = 7,
    
        _6 = 6,
    
        _5 = 5,
    
        _4 = 4,
    
        _3 = 3,
    
        _2 = 2,
    
        _1 = 1,
    
    }
}