using YuzuDelivery.Umbraco.BlockList;
using YuzuDelivery.Umbraco.Core;
using YuzuDelivery.Umbraco.Forms;
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.23.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace YuzuDelivery.ViewModels
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.23.0 (Newtonsoft.Json v13.0.0.0)")]
    [YuzuMap("DataFormBuilderRow")]
    public partial class vmSub_DataFormBuilderRow 
    {
        [Newtonsoft.Json.JsonProperty("columns", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object Columns { get; set; }
    
    
    }
}