using YuzuDelivery.Umbraco.BlockList;
using YuzuDelivery.Umbraco.Core;
using YuzuDelivery.Umbraco.Forms;
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.23.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace YuzuDelivery.ViewModels
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.23.0 (Newtonsoft.Json v13.0.0.0)")]
    [YuzuMap("GridBuilderColumnConfig")]
    public partial class vmBlock_GridBuilderColumnConfig 
    {
        [Newtonsoft.Json.JsonProperty("hide", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public vmSub_GridBuilderColumnConfigVmBlock_GridBuilderColumnConfigHide Hide { get; set; }
    
        [Newtonsoft.Json.JsonProperty("ColumnItemsVerticalPlacement", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public vmSub_GridBuilderColumnConfigVmBlock_GridBuilderColumnConfigColumnItemsVerticalPlacement ColumnItemsVerticalPlacement { get; set; } = YuzuDelivery.ViewModels.vmSub_GridBuilderColumnConfigVmBlock_GridBuilderColumnConfigColumnItemsVerticalPlacement.ContentCenter;
    
        [Newtonsoft.Json.JsonProperty("ColumnItemsHorizontalPlacement", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public vmSub_GridBuilderColumnConfigVmBlock_GridBuilderColumnConfigColumnItemsHorizontalPlacement ColumnItemsHorizontalPlacement { get; set; } = YuzuDelivery.ViewModels.vmSub_GridBuilderColumnConfigVmBlock_GridBuilderColumnConfigColumnItemsHorizontalPlacement.PlaceItemsCenter;
    
        [Newtonsoft.Json.JsonProperty("_ref", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string _ref { get; set; }
    
        [Newtonsoft.Json.JsonProperty("_modifiers", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.List<string> _modifiers { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.23.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum vmSub_GridBuilderColumnConfigVmBlock_GridBuilderColumnConfigHide
    {
        [System.Runtime.Serialization.EnumMember(Value = @"")]
        Empty = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"hidden lg:grid")]
        Hidden_lgGrid = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"grid lg:hidden")]
        Grid_lgHidden = 2,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.23.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum vmSub_GridBuilderColumnConfigVmBlock_GridBuilderColumnConfigColumnItemsVerticalPlacement
    {
        [System.Runtime.Serialization.EnumMember(Value = @"content-start")]
        ContentStart = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"content-center")]
        ContentCenter = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"content-end")]
        ContentEnd = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"content-between")]
        ContentBetween = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"content-around")]
        ContentAround = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"content-evenly")]
        ContentEvenly = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"content-stretch")]
        ContentStretch = 6,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.0.23.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum vmSub_GridBuilderColumnConfigVmBlock_GridBuilderColumnConfigColumnItemsHorizontalPlacement
    {
        [System.Runtime.Serialization.EnumMember(Value = @"place-items-start")]
        PlaceItemsStart = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"place-items-center")]
        PlaceItemsCenter = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"place-items-end")]
        PlaceItemsEnd = 2,
    
    }
}